backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "gallery"
    label: "Gallery"
    files:
      - name: "gallery"
        label: "Gallery Images"
        file: "data/gallery.json"
        format: "json"
        fields:
          - label: "Images"
            name: "images"
            widget: list
            summary: "{{fields.alt}}"
            fields:
              - label: "Image"
                name: "src"
                widget: image
              - label: "Alt Text"
                name: "alt"
                widget: string
              - label: "Caption"
                name: "caption"
                widget: string
                required: false
